modLoader="javafml"
loaderVersion="[44,)"
license="GNU LGPLv3"

[[mods]]
    modId="axolootl"
    version="19.3.0.0"
    displayName="Axolootl"
    authors="skyjay1"
    credits=""
    description='''Resourceful little predators'''

[[dependencies.axolootl]]
    modId="forge"
    mandatory=true
    versionRange="[44,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.axolootl]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.axolootl]]
    modId="geckolib3"
    mandatory=true
    versionRange="[4.0.6,)"
    ordering="NONE"
    side="BOTH"